version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3037:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"